#! /bin/bash
cd ../
rm telegram-bot.zip
# add packages
pip install --target ./package -r requirements.txt
pip install --target ./package .

# add files to package
cd package
zip -r9 ../telegram-bot.zip .
cd ../
# cleanup intermediate
rm -Rvf package
