#! /bin/bash
cd ../
rm telegram-bot.zip
# add package
pip install --target ./package .

# add files to package
cd package || exit
zip -r9 ../telegram-bot.zip .
cd ../
# cleanup intermediate
rm -Rf package
