#! /bin/bash
#set -eo pipefail

cd ../
rm telegram-bot-base.zip
# add package
pip install --target ./package/python -r requirements.txt

# add files to package
cd package || exit
zip -r9 ../telegram-bot-base.zip .
cd ../
# cleanup intermediate
rm -Rf package
